-- AlterTable
ALTER TABLE "Registration" ADD COLUMN     "isVerified" BOOLEAN DEFAULT false,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "mobile" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "Age" DROP NOT NULL,
ALTER COLUMN "Course" DROP NOT NULL,
ALTER COLUMN "screenshotlink" DROP NOT NULL;
